development:
  adapter: mysql2
  database: photo_cywoniuk_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: photo_cywoniuk_test
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

staging:
  adapter: mysql2
  database: photo_cywoniuk_staging
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: photo_cywoniuk_production
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost
